### ISSUE TITLE
Keywords should be highlighted case-insensitively.

### ISSUE THREAD

**Issue by nelsonic** [dwyl/search-result-keyword-highlighter#4]
As a person searching for a keyword I want it to be `highlighted` regardless of _case_.
so a search for `Java`, `javA` or `java` will highlight `JAVA` or `JaVa` in the search result.

**Comment by iteles** [comment]
I was just reading about the regex flags the other day! `/i` at the end of your regex will ignore case (which of course you knew, but I wanted to show I did too :stuck_out_tongue: )

Also, reading through [my notes on regex](https://github.com/iteles/Javascript-the-Good-Parts-notes#an-example), it's useful to remember hyphens in the search terms will also need to be escaped with a backslash `\` :blush:

**Comment by nelsonic** [comment]
I don't have a test case with hyphens. feel free to add one. :+1:

**Comment by nelsonic** [comment]
Done.
