### ISSUE TITLE
As a Developer do I want to define my own custom HTML Tag and CSS to apply to the highlighted keyword?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/search-result-keyword-highlighter#5]
As a developer do I want control over which tag is used in the html markup to highlight the keywords?

**Comment by iteles** [comment]
:+1: I'm a fan of your chosen `<b class="highlight"></b>` (although I might name the class `search-highlight` personally). 

But as a non-MVP feature, it would be great to allow developers to choose their HTML element and class to prevent clashes in large existing codebases (and styling nightmares).

**Comment by nelsonic** [comment]
Agreed that its not an MVP feature. So I'm leaving it out. If we feel the need to change the markup or CSS its _very_ easy to add later. :+1:

**Comment by nelsonic** [comment]
Closing for now. there's a link to it in the code. if anyone wants this feature we can _easily_ add it. :+1:
