### ISSUE TITLE
loop vs replace function

### ISSUE THREAD

**Issue by SimonLab** [dwyl/search-result-keyword-highlighter#9]
Why using a [for loop](https://github.com/dwyl/search-result-keyword-highlighter/blob/bd572d3962c4d20f0fd78f12da7ed56475083935/lib/keyword-highlighter.js#L33-L39) to find the keywords in the text instead of using the replace function?

**Comment by nelsonic** [comment]
Great question @SimonLab!
I _was_ using a `replace()` in an earlier version. See: https://github.com/dwyl/search-result-keyword-highlighter/blob/00c813da4f09e07fc2c969b06384e25465e77541/lib/keyword-highlighter.js#L30

if the keyword someone searched for is typed in `lowercase` then all the _occurrences_ of that keyword on the page will be _down-cased_ when they are highlighted. 
e.g: 

``` js
var text = "I write JavaScript Code while drinking JAVA Coffee";
var highlighted = h('java', text);
console.log(highlighted);
```

``` html
I write <b class='highlight'>java</b>Script Code 
while drinking <b class='highlight'>java</b> Coffee
```

Which would mean that people/proper/company names would be lower-cased in search results:
e.g: 

``` js
var text = "My Name is John, I am a JavaScript Developer at XYZ Co. in London";
var highlighted = h('John London', text);
console.log(highlighted);
```

Would output:

``` html
My Name is <b class='highlight'>john</b>, I am a JavaScript Developer 
at XYZ Co. in <b class='highlight'>london</b>
```

### Original Text _Before_ Highlighting keywords `John` & `London`

My Name is John, I am a JavaScript Developer at XYZ Co. in London

### Keywords are lowercased during substitution (_undesirable_)

My Name is **john**, I am a JavaScript Developer at XYZ Co. in **london**

### Keywords are not affected during substitution (_the desired output_)

My Name is **John**, I am a JavaScript Developer at XYZ Co. in **London**

> If you have _time_ :clock1:  to play with this to make the algorithm faster, while still having the text highlighted _no-destructively_ please do! :+1: 

Also, I was seeing the issue: https://github.com/dwyl/search-result-keyword-highlighter/issues/6 when doing `replace()` where there were multiple occurrences of the same keyword in the text.

**Comment by nelsonic** [comment]
@SimonLab does that answer your question?

**Comment by SimonLab** [comment]
@nelsonic yes it does, thanks for the explanation! Thanks @rjmk for your functional view!
